require:
  - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    
Lint/MissingSuper:
  Enabled: false

MultipleMemoizedHelpers:
  Enabled: false
